### ISSUE TITLE
Master branch does not work on Plone 5

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.plonetruegallery#66]
The master branch does not start on Plone 5. Tried on 5.1. I tried fixing things, starting with lots and lots of cleanup. See branch [`plone5`](https://github.com/collective/collective.plonetruegallery/commits/plone5).
I also enabled Travis, which has not run in a year.

The immediate problem was that since the last master commit 50ba82d7d7e32479d6fb36f0b1ac8d27be6d1c3e by Jens, I get `ImportError: cannot import name PTGMessageFactory` on startup. I fixed that.

Current failure is that `plone.app.form` is missing. Tried fixing that too with zcml conditions, but too much would need to be switched off. The portlet would need to be switched to `z3c.form`, which should be relatively straightforward.

@jensens Your last commit has the message "make it start in Python 3 - won't work so far".  Did the master branch actually start for you?  How?

**Comment by jensens** [comment]
@mauritsvanrees no, I gave up after a I found the bunch of plugins. I dont think its the path to take to upgrade here. Today a react component over some light weight backend configuration would be better.

**Comment by mauritsvanrees** [comment]
Okay, thanks for the info.
I have reverted your changes on master, and did some minimal fixes so things at least work on Plone 4.3 again, maybe even on Travis.

**Comment by mauritsvanrees** [comment]
@tkimnguyen In commit 259bf7c119c238f3c496f4bbb57df8e60c1043c9 you claimed Plone 5 compatibility. And @petschki, in commit b55280813d080533781c822caf57c3028bbcfd3a you apparently "fixed css resource cooking" in Plone 5.1.

That was two years ago, and today it fails to start, both for me and for Jens. I only tried on 5.1 and 5.2.
Are you still using `collective.plonetruegallery` and is it working for you an a Plone 5 version?
If so, it could help if you jump in and fix the buildout and Travis. I did some minimal fixes, which at least make things work locally with Plone 4.3, though not on Travis.

At this point I am not interested in further work on this, but I thought I should at least ping you to let you know that this repository is not in top shape.

**Comment by petschki** [comment]
I never used it in production. Just tried to quick-fix the resource cooking for plone 5.1 but this was only an issue when cooking TTW in development mode... I'm sorry but I'm not able to make more stuff here ...

**Comment by fulv** [comment]
Like a babe in the woods, I installed this on a 5.0.3.1 site in June of 2019.  I had not seen this or other issues, otherwise I probably would have steered clear.  But the bottom line is it's been running on production ever since, as a source checkout from master.
Now I'm trying to upgrade to 5.2 and the problems are cropping up.  I did an intermediate step via 5.1, and it was working fine there.  
At this point, though, I'm thinking of dropping it, given the problems you have been seeing.
Let me know if you want any details of my installation.
