### ISSUE TITLE
Plone 5.1-latest installation

### ISSUE THREAD

**Issue by petschki** [collective/collective.plonetruegallery#61]
I've added version 3.4.8 to a fresh plone 5.1-latest buildout and get this traceback when starting the instance:

```
2017-11-15 07:20:29 INFO ZServer HTTP server started at Wed Nov 15 07:20:29 2017
	Hostname: 0.0.0.0
	Port: 8008
2017-11-15 07:20:32 INFO ZEO.ClientStorage zeostorage ClientStorage (pid=30610) created RW/normal for storage: '1'
2017-11-15 07:20:32 INFO ZEO.cache created temporary cache file '<fdopen>'
2017-11-15 07:20:32 INFO ZEO.asyncio.base Connected Protocol(('127.0.0.1', 8001), '1', False)
2017-11-15 07:20:32 INFO ZEO.ClientStorage zeostorage Connected to storage: ('localhost.localdomain', 8001)
Traceback (most recent call last):
  File "/home/plone/zope_buildout/parts/instance/bin/interpreter", line 322, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 120, in startup
    load_zcml()
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/plone/.buildout/eggs/Zope2-2.13.26-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/home/plone/python-2.7.14/lib/python2.7/xml/sax/expatreader.py", line 373, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 232, in startElementNS
    self.context.begin(name, data, info)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 555, in begin
    self.stack.append(self.stack[-1].contained(__name, __data, __info))
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 856, in contained
    return RootStackItem.contained(self, name, data, info)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 727, in contained
    adapter = factory(self.context, data, info)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1224, in factory
    return ComplexStackItem(self, context, data, info)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 970, in __init__
    args = toargs(newcontext, meta.schema, data)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1397, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py", line 137, in fromUnicode
    value = self.context.resolve(name)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 179, in resolve
    mod = __import__(mname, *_import_chickens)
  File "/home/plone/.buildout/eggs/Products.CMFDefault-2.3.0b2-py2.7.egg/Products/CMFDefault/SyndicationTool.py", line 31, in <module>
    from Products.CMFCore.interfaces import ISyndicationTool, ISyndicationInfo
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/plone/zope_buildout/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/plone/.buildout/eggs/Products.CMFDefault-2.3.0b2-py2.7.egg/Products/CMFDefault/configure.zcml", line 26.2
    ImportError: cannot import name ISyndicationInfo
```

when I remove the `collective.plonetruegallery` line from the eggs, everything works fine. Maybe an issue with the `install_requires` of setup.py?

**Comment by petschki** [comment]
after some more investigations I've found out, that Products.CMFDefault is no dependency in Plone>=5 anymore and therefore is unpinned in versions.cfg. That's why I've got CMFDefault==2.3.0b2 which isn't compatible with CMFCore. I'll try to find out, where CMFDefault gets a dependency here ...

**Comment by petschki** [comment]
PS: quickfix for anyone who uses a fresh Plone>=5 buildout is to pin `Products.CMFDefault==2.2.4`

**Comment by zachwelch** [comment]
I too want to use this add-on with 5.1-latest. I got ``Products.CMFDefault==2.2.4``, so my trouble only started when going to run the quickinstaller. When I try to install on a site, I get a traceback, and some detective work led me to find this issue and PR #62. That commit (on master) makes it go again, so the question that begs to be asked.... when will 3.4.9 be released?!?

**Comment by zachwelch** [comment]
Well, I guess there are still other issues that need to be fixed to make this add-on work with ``5.1.x``. For example, I discovered that having this add-on installed in an otherwise a stock ``traning_buildout`` causes all of the ``++add++`` forms to appear empty. Removing it from ``buildout.cfg`` restores those forms. This add-on is referenced explicitly in the Mastering Plone training module, so these bugs create a bit of a bump in that learning curve.

**Comment by pbauer** [comment]
@zachwelch sorry for that. The issue with empty `++add++` forms is due to this issue: https://docs.plone.org/develop/addons/upgrade_to_51.html#cmfdefault-removal
